# -*- coding: utf-8 -*-
"""Online Shopping Intention.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Pr-9rlCK5uBsjnRQRjmohpxM4VXB0f1
"""

!pip install -q shap kaleido

import warnings
warnings.filterwarnings("ignore")

import os
import time
import joblib
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from sklearn.model_selection import train_test_split, StratifiedKFold, RandomizedSearchCV, cross_val_score
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.feature_selection import VarianceThreshold, mutual_info_classif, RFE
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score, roc_auc_score,
    confusion_matrix, roc_curve, precision_recall_curve, classification_report,
    matthews_corrcoef, balanced_accuracy_score
)
from sklearn.inspection import permutation_importance

import xgboost as xgb
from lightgbm import LGBMClassifier

import shap

RANDOM_SEED = 42
np.random.seed(RANDOM_SEED)

sns.set_style("whitegrid")
plt.rcParams["figure.dpi"] = 110
plt.rcParams["axes.titlesize"] = 13
plt.rcParams["axes.titleweight"] = "bold"

os.makedirs("figures", exist_ok=True)
os.makedirs("outputs", exist_ok=True)

print("Libraries imported successfully.")

"""# Load Dataset"""

DATA_PATH = "online_shoppers_intention.csv"
df = pd.read_csv(DATA_PATH)

print("Shape:", df.shape)
display(df.head())
display(df.tail())
print("\nColumns:\n", df.columns.tolist())
print("\nInfo:")
df.info()
display(df.describe(include="all").T)
print("\nData types:\n", df.dtypes)

"""# Exploratory Data Analysis"""

def missing_values_table(data):
    miss = data.isnull().sum()
    pct = (miss / len(data)) * 100
    table = pd.DataFrame({"Missing Count": miss, "Missing %": pct})
    return table[table["Missing Count"] > 0].sort_values("Missing %", ascending=False)

miss_table = missing_values_table(df)
print("Missing Values Table:")
display(miss_table if not miss_table.empty else "No missing values found.")

plt.figure(figsize=(12, 6))
sns.heatmap(df.isnull(), cbar=False, cmap="viridis")
plt.title("Missing Values Heatmap")
plt.tight_layout()
plt.savefig("figures/01_missing_heatmap.png")
plt.show()

dup_count = df.duplicated().sum()
print(f"Duplicate rows: {dup_count}")

"""## target distribution & class imbalance"""

fig, ax = plt.subplots(1, 2, figsize=(14, 5))
df["Revenue"].value_counts().plot(kind="bar", ax=ax[0], color=["#4C72B0", "#DD8452"])
ax[0].set_title("Target Distribution (Revenue)")
ax[0].set_xlabel("Revenue"); ax[0].set_ylabel("Count")

df["Revenue"].value_counts(normalize=True).plot(kind="pie", autopct="%1.1f%%", ax=ax[1],
    colors=["#4C72B0", "#DD8452"])
ax[1].set_title("Class Imbalance Chart")
ax[1].set_ylabel("")
plt.tight_layout()
plt.savefig("figures/02_target_distribution.png")
plt.show()

"""## numerical histograms"""

num_cols = df.select_dtypes(include=[np.number]).columns.tolist()

df[num_cols].hist(figsize=(18, 14), bins=30, color="#4C72B0", edgecolor="black")
plt.suptitle("Numerical Feature Distributions", fontsize=16, fontweight="bold")
plt.tight_layout()
plt.savefig("figures/03_numerical_histograms.png")
plt.show()

"""## categorical countplots"""

cat_cols = ["Month", "OperatingSystems", "Browser", "Region", "TrafficType",
            "VisitorType", "Weekend"]

fig, axes = plt.subplots(4, 2, figsize=(16, 20))
axes = axes.flatten()
for i, col in enumerate(cat_cols):
    sns.countplot(data=df, x=col, hue="Revenue", ax=axes[i], palette="Set2")
    axes[i].set_title(f"{col} vs Revenue")
    axes[i].tick_params(axis="x", rotation=45)
fig.delaxes(axes[-1])
plt.tight_layout()
plt.savefig("figures/04_categorical_countplots.png")
plt.show()

"""## correlation matrix"""

plt.figure(figsize=(14, 10))
corr = df[num_cols].corr()
sns.heatmap(corr, annot=True, fmt=".2f", cmap="coolwarm", square=True, linewidths=0.5)
plt.title("Correlation Matrix — Numerical Features")
plt.tight_layout()
plt.savefig("figures/05_correlation_matrix.png")
plt.show()

"""## boxplots & violin plots"""

key_features = ["ProductRelated_Duration", "BounceRates", "ExitRates", "PageValues"]

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()
for i, col in enumerate(key_features):
    sns.boxplot(data=df, x="Revenue", y=col, ax=axes[i], palette="Set3")
    axes[i].set_title(f"Boxplot — {col} by Revenue")
plt.tight_layout()
plt.savefig("figures/06_boxplots.png")
plt.show()

fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()
for i, col in enumerate(key_features):
    sns.violinplot(data=df, x="Revenue", y=col, ax=axes[i], palette="Pastel1")
    axes[i].set_title(f"Violin Plot — {col} by Revenue")
plt.tight_layout()
plt.savefig("figures/07_violinplots.png")
plt.show()

"""# Data Cleaning"""

df_clean = df.copy()

# Remove duplicates
before = len(df_clean)
df_clean = df_clean.drop_duplicates().reset_index(drop=True)
print(f"Removed {before - len(df_clean)} duplicate rows.")

# Handle missing values (median for numeric, mode for categorical)
for col in df_clean.columns:
    if df_clean[col].isnull().sum() > 0:
        if df_clean[col].dtype in [np.float64, np.int64]:
            df_clean[col].fillna(df_clean[col].median(), inplace=True)
        else:
            df_clean[col].fillna(df_clean[col].mode()[0], inplace=True)

# Convert boolean columns
df_clean["Weekend"] = df_clean["Weekend"].astype(bool).astype(int)
df_clean["Revenue"] = df_clean["Revenue"].astype(bool).astype(int)

# Correct data types
int_like_cols = ["OperatingSystems", "Browser", "Region", "TrafficType"]
for col in int_like_cols:
    df_clean[col] = df_clean[col].astype(int)

print("Missing values after cleaning:", df_clean.isnull().sum().sum())
print("Final shape:", df_clean.shape)
display(df_clean.dtypes)

"""# Feature Engineering"""

def engineer_features(data):
    d = data.copy()

    # Interaction features
    d["Total_Pages_Viewed"] = d["Administrative"] + d["Informational"] + d["ProductRelated"]
    d["Total_Duration"] = (d["Administrative_Duration"] + d["Informational_Duration"]
                            + d["ProductRelated_Duration"])

    # Session duration ratio (avoid divide by zero)
    d["Avg_Duration_Per_Page"] = d["Total_Duration"] / d["Total_Pages_Viewed"].replace(0, np.nan)
    d["Avg_Duration_Per_Page"] = d["Avg_Duration_Per_Page"].fillna(0)

    # Browsing intensity: product pages relative to total pages
    d["ProductRelated_Ratio"] = d["ProductRelated"] / d["Total_Pages_Viewed"].replace(0, np.nan)
    d["ProductRelated_Ratio"] = d["ProductRelated_Ratio"].fillna(0)

    # Page efficiency: PageValues relative to exit rate
    d["Page_Efficiency"] = d["PageValues"] / (d["ExitRates"] + 1e-5)

    # Bounce-to-exit ratio
    d["Bounce_Exit_Ratio"] = d["BounceRates"] / (d["ExitRates"] + 1e-5)

    # Weekend behaviour flag interacting with visitor type
    d["Weekend_Returning"] = ((d["Weekend"] == 1) &
                               (d["VisitorType"] == "Returning_Visitor")).astype(int)

    # Month seasonality grouping
    holiday_months = ["Nov", "Dec", "May"]
    d["Is_Holiday_Season"] = d["Month"].isin(holiday_months).astype(int)

    return d

df_fe = engineer_features(df_clean)
print("New features created:")
new_cols = ["Total_Pages_Viewed", "Total_Duration", "Avg_Duration_Per_Page",
            "ProductRelated_Ratio", "Page_Efficiency", "Bounce_Exit_Ratio",
            "Weekend_Returning", "Is_Holiday_Season"]
display(df_fe[new_cols].head())

"""## encoding and feature selection"""

df_encoded = pd.get_dummies(df_fe, columns=["Month", "VisitorType"], drop_first=True)

# convert any resulting bool columns to int
bool_cols = df_encoded.select_dtypes(include="bool").columns
df_encoded[bool_cols] = df_encoded[bool_cols].astype(int)

print("Shape after encoding:", df_encoded.shape)
display(df_encoded.head())

X = df_encoded.drop(columns=["Revenue"])
y = df_encoded["Revenue"]

# Variance Threshold
vt = VarianceThreshold(threshold=0.01)
vt.fit(X)
low_var_features = X.columns[~vt.get_support()].tolist()
print("Low-variance features flagged:", low_var_features)

# Mutual Information
mi_scores = mutual_info_classif(X, y, random_state=RANDOM_SEED)
mi_series = pd.Series(mi_scores, index=X.columns).sort_values(ascending=False)

plt.figure(figsize=(10, 8))
mi_series.head(20).plot(kind="barh", color="#55A868")
plt.gca().invert_yaxis()
plt.title("Top 20 Features — Mutual Information Score")
plt.xlabel("MI Score")
plt.tight_layout()
plt.savefig("figures/11_mutual_information.png")
plt.show()

# Recursive Feature Elimination (using a light estimator for speed)
rfe_estimator = LogisticRegression(max_iter=1000, random_state=RANDOM_SEED)
rfe = RFE(rfe_estimator, n_features_to_select=15)
rfe.fit(X, y)
rfe_selected = X.columns[rfe.support_].tolist()
print("\nRFE selected features:", rfe_selected)

# Drop near-zero-variance features only (keep everything else — models handle relevance)
X = X.drop(columns=[c for c in low_var_features if c in X.columns])
print("\nFinal feature count:", X.shape[1])

"""# Data Preprocessing"""

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, stratify=y, random_state=RANDOM_SEED
)

print("Train shape:", X_train.shape, " Test shape:", X_test.shape)
print("Train class balance:\n", y_train.value_counts(normalize=True))

numeric_features = X_train.select_dtypes(include=[np.number]).columns.tolist()

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_features)
    ],
    remainder="passthrough"
)

preprocessor.fit(X_train)
X_train_processed = preprocessor.transform(X_train)
X_test_processed = preprocessor.transform(X_test)

joblib.dump(preprocessor, "outputs/preprocessor.pkl")
print("Preprocessing pipeline saved.")

"""# Machine Learning Models"""

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_SEED)

param_grids = {
    "Logistic Regression": (
        LogisticRegression(max_iter=2000, random_state=RANDOM_SEED),
        {"C": [0.01, 0.1, 1, 10, 100], "penalty": ["l2"], "solver": ["lbfgs"]}
    ),
    "Decision Tree": (
        DecisionTreeClassifier(random_state=RANDOM_SEED),
        {"max_depth": [3, 5, 7, 10, 15, None],
         "min_samples_split": [2, 5, 10],
         "min_samples_leaf": [1, 2, 4]}
    ),
    "Random Forest": (
        RandomForestClassifier(random_state=RANDOM_SEED),
        {"n_estimators": [100, 200, 300],
         "max_depth": [5, 10, 15, None],
         "min_samples_split": [2, 5, 10],
         "max_features": ["sqrt", "log2"]}
    ),
    "XGBoost": (
        xgb.XGBClassifier(random_state=RANDOM_SEED, eval_metric="logloss", use_label_encoder=False),
        {"n_estimators": [100, 200, 300],
         "max_depth": [3, 5, 7],
         "learning_rate": [0.01, 0.05, 0.1, 0.2],
         "subsample": [0.7, 0.8, 1.0]}
    ),
    "LightGBM": (
        LGBMClassifier(random_state=RANDOM_SEED, verbose=-1),
        {"n_estimators": [100, 200, 300],
         "max_depth": [3, 5, 7, -1],
         "learning_rate": [0.01, 0.05, 0.1, 0.2],
         "num_leaves": [15, 31, 63]}
    ),
}

trained_models = {}
model_results = []

for name, (estimator, grid) in param_grids.items():
    print(f"\nTraining: {name}")
    search = RandomizedSearchCV(
        estimator, grid, n_iter=15, cv=cv, scoring="roc_auc",
        random_state=RANDOM_SEED, n_jobs=-1, verbose=0
    )

    start_train = time.time()
    search.fit(X_train_processed, y_train)
    train_time = time.time() - start_train

    best_model = search.best_estimator_
    trained_models[name] = best_model

    start_pred = time.time()
    y_pred = best_model.predict(X_test_processed)
    pred_time = time.time() - start_pred

    y_proba = best_model.predict_proba(X_test_processed)[:, 1]
    cv_score = search.best_score_

    model_results.append({
        "Model": name,
        "Best Params": search.best_params_,
        "Training Time (s)": round(train_time, 3),
        "Prediction Time (s)": round(pred_time, 4),
        "CV ROC AUC": round(cv_score, 4),
        "y_pred": y_pred,
        "y_proba": y_proba
    })

    print(f"  Best Params: {search.best_params_}")
    print(f"  CV ROC AUC: {cv_score:.4f} | Train Time: {train_time:.2f}s | Pred Time: {pred_time:.4f}s")

print("\nAll models trained.")

"""# Model Evaluation"""

evaluation_rows = []

for res in model_results:
    name = res["Model"]
    y_pred = res["y_pred"]
    y_proba = res["y_proba"]

    evaluation_rows.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1 Score": f1_score(y_test, y_pred),
        "ROC AUC": roc_auc_score(y_test, y_proba),
        "MCC": matthews_corrcoef(y_test, y_pred),
        "Balanced Accuracy": balanced_accuracy_score(y_test, y_pred),
        "CV ROC AUC": res["CV ROC AUC"],
        "Training Time (s)": res["Training Time (s)"],
        "Prediction Time (s)": res["Prediction Time (s)"]
    })

    print(f"\n{'='*60}\n{name}\n{'='*60}")
    print(classification_report(y_test, y_pred))

comparison_df = pd.DataFrame(evaluation_rows).sort_values("ROC AUC", ascending=False).reset_index(drop=True)
comparison_df.insert(0, "Rank", range(1, len(comparison_df) + 1))
display(comparison_df.drop(columns=[]).style.background_gradient(subset=["ROC AUC", "Accuracy", "F1 Score"], cmap="Greens"))

comparison_df.to_csv("outputs/comparison_results.csv", index=False)

"""## confusion matrices"""

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
axes = axes.flatten()
for i, res in enumerate(model_results):
    cm = confusion_matrix(y_test, res["y_pred"])
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", ax=axes[i],
                xticklabels=["No Purchase", "Purchase"], yticklabels=["No Purchase", "Purchase"])
    axes[i].set_title(f"Confusion Matrix — {res['Model']}")
    axes[i].set_xlabel("Predicted"); axes[i].set_ylabel("Actual")
fig.delaxes(axes[-1])
plt.tight_layout()
plt.savefig("figures/12_confusion_matrices.png")
plt.show()

"""## ROC curves & PR curves"""

plt.figure(figsize=(9, 7))
for res in model_results:
    fpr, tpr, _ = roc_curve(y_test, res["y_proba"])
    auc_val = roc_auc_score(y_test, res["y_proba"])
    plt.plot(fpr, tpr, label=f"{res['Model']} (AUC={auc_val:.3f})")
plt.plot([0, 1], [0, 1], "k--", label="Random Classifier")
plt.xlabel("False Positive Rate"); plt.ylabel("True Positive Rate")
plt.title("ROC Curves — All Models")
plt.legend(loc="lower right")
plt.tight_layout()
plt.savefig("figures/13_roc_curves.png")
plt.show()

plt.figure(figsize=(9, 7))
for res in model_results:
    prec, rec, _ = precision_recall_curve(y_test, res["y_proba"])
    plt.plot(rec, prec, label=res["Model"])
plt.xlabel("Recall"); plt.ylabel("Precision")
plt.title("Precision-Recall Curves — All Models")
plt.legend(loc="lower left")
plt.tight_layout()
plt.savefig("figures/14_pr_curves.png")
plt.show()

!pip install -q kaleido

metrics_long = comparison_df.melt(
    id_vars="Model", value_vars=["Accuracy", "Precision", "Recall", "F1 Score", "ROC AUC"],
    var_name="Metric", value_name="Score"
)
fig = px.bar(metrics_long, x="Model", y="Score", color="Metric", barmode="group",
             title="Model Comparison Across Key Metrics", template="plotly_white")
fig.show()

best_row = comparison_df.iloc[0]
best_model_name = best_row["Model"]
best_model = trained_models[best_model_name]

print(f"Best Model Selected: {best_model_name}")
print(f"ROC AUC: {best_row['ROC AUC']:.4f}")
print(f"""
Justification: {best_model_name} achieved the highest ROC AUC ({best_row['ROC AUC']:.4f})
on the held-out test set, indicating the strongest ability to separate purchasing
from non-purchasing sessions across all probability thresholds. It also maintains
competitive Accuracy ({best_row['Accuracy']:.4f}) and F1 Score ({best_row['F1 Score']:.4f}),
and its cross-validated score ({best_row['CV ROC AUC']:.4f}) is consistent with the
test performance, suggesting good generalisation rather than overfitting.
""")

joblib.dump(best_model, "outputs/best_model.pkl")
print("Best model saved as outputs/best_model.pkl")

"""# Explainability"""

feature_names = numeric_features + [c for c in X.columns if c not in numeric_features]

if hasattr(best_model, "feature_importances_"):
    importances = best_model.feature_importances_
    imp_series = pd.Series(importances, index=feature_names).sort_values(ascending=False)

    plt.figure(figsize=(10, 8))
    imp_series.head(20).plot(kind="barh", color="#C44E52")
    plt.gca().invert_yaxis()
    plt.title(f"Top 20 Feature Importances — {best_model_name}")
    plt.tight_layout()
    plt.savefig("figures/15_feature_importance.png")
    plt.show()

perm_result = permutation_importance(best_model, X_test_processed, y_test,
                                       n_repeats=10, random_state=RANDOM_SEED, n_jobs=-1)
perm_series = pd.Series(perm_result.importances_mean, index=feature_names).sort_values(ascending=False)

plt.figure(figsize=(10, 8))
perm_series.head(20).plot(kind="barh", color="#8172B2")
plt.gca().invert_yaxis()
plt.title(f"Top 20 Permutation Importances — {best_model_name}")
plt.tight_layout()
plt.savefig("figures/16_permutation_importance.png")
plt.show()

"""# SHAP"""

explainer = shap.Explainer(best_model, X_train_processed, feature_names=feature_names)
shap_values = explainer(X_test_processed[:500])   # subsample for speed

plt.figure()
shap.summary_plot(shap_values, X_test_processed[:500], feature_names=feature_names, show=False)
plt.title("SHAP Summary Plot")
plt.tight_layout()
plt.savefig("figures/18_shap_summary.png")
plt.show()

plt.figure()
shap.summary_plot(shap_values, X_test_processed[:500], feature_names=feature_names,
                   plot_type="bar", show=False)
plt.title("SHAP Feature Importance (Bar)")
plt.tight_layout()
plt.savefig("figures/19_shap_bar.png")
plt.show()

"""# Error Analysis"""

best_pred = None
for res in model_results:
    if res["Model"] == best_model_name:
        best_pred = res
        break

y_pred_best = best_pred["y_pred"]
y_proba_best = best_pred["y_proba"]

results_df = X_test.copy()
results_df["Actual"] = y_test.values
results_df["Predicted"] = y_pred_best
results_df["Probability"] = y_proba_best

false_positives = results_df[(results_df["Actual"] == 0) & (results_df["Predicted"] == 1)]
false_negatives = results_df[(results_df["Actual"] == 1) & (results_df["Predicted"] == 0)]
misclassified = results_df[results_df["Actual"] != results_df["Predicted"]]

print(f"False Positives: {len(false_positives)}")
print(f"False Negatives: {len(false_negatives)}")
print(f"Total Misclassified: {len(misclassified)} ({len(misclassified)/len(results_df)*100:.2f}%)")

fig, ax = plt.subplots(1, 2, figsize=(14, 5))
sns.histplot(results_df[results_df["Actual"] == 1]["Probability"], bins=30, color="green",
             ax=ax[0], kde=True)
ax[0].set_title("Predicted Probability — Actual Purchasers")
sns.histplot(results_df[results_df["Actual"] == 0]["Probability"], bins=30, color="red",
             ax=ax[1], kde=True)
ax[1].set_title("Predicted Probability — Actual Non-Purchasers")
plt.tight_layout()
plt.savefig("figures/20_probability_distributions.png")
plt.show()

results_df.to_csv("outputs/predictions.csv", index=False)
print("\nSample misclassified rows:")
display(misclassified.head(10))

"""# Streamlit App Preparation, Build & Deployment Files"""

app_code = '''
import streamlit as st
import pandas as pd
import numpy as np
import joblib
import plotly.graph_objects as go

st.set_page_config(page_title="Online Shopper Purchase Predictor", layout="wide", page_icon="🛒")

@st.cache_resource
def load_artifacts():
    model = joblib.load("best_model.pkl")
    preprocessor = joblib.load("preprocessor.pkl")
    return model, preprocessor

model, preprocessor = load_artifacts()

st.title("🛒 Online Shopper Purchase Intention Predictor")
st.markdown("Predict whether a browsing session will end in a purchase, using a trained ML model.")

st.sidebar.header("Session Input Features")

def user_input():
    admin = st.sidebar.number_input("Administrative pages viewed", 0, 30, 0)
    admin_dur = st.sidebar.number_input("Administrative duration (s)", 0.0, 3000.0, 0.0)
    info = st.sidebar.number_input("Informational pages viewed", 0, 30, 0)
    info_dur = st.sidebar.number_input("Informational duration (s)", 0.0, 3000.0, 0.0)
    product = st.sidebar.number_input("Product related pages viewed", 0, 700, 1)
    product_dur = st.sidebar.number_input("Product related duration (s)", 0.0, 15000.0, 0.0)
    bounce = st.sidebar.slider("Bounce rate", 0.0, 0.2, 0.02)
    exit_rate = st.sidebar.slider("Exit rate", 0.0, 0.2, 0.02)
    page_values = st.sidebar.number_input("Page values", 0.0, 400.0, 0.0)
    special_day = st.sidebar.slider("Special day closeness", 0.0, 1.0, 0.0)
    weekend = st.sidebar.checkbox("Weekend session")
    visitor_type = st.sidebar.selectbox("Visitor type", ["Returning_Visitor", "New_Visitor", "Other"])
    month = st.sidebar.selectbox("Month", ["Feb","Mar","May","June","Jul","Aug","Sep","Oct","Nov","Dec"])
    os_ = st.sidebar.number_input("Operating system code", 1, 8, 1)
    browser = st.sidebar.number_input("Browser code", 1, 13, 1)
    region = st.sidebar.number_input("Region code", 1, 9, 1)
    traffic = st.sidebar.number_input("Traffic type code", 1, 20, 1)

    total_pages = admin + info + product
    total_duration = admin_dur + info_dur + product_dur
    avg_dur_page = total_duration / total_pages if total_pages > 0 else 0
    product_ratio = product / total_pages if total_pages > 0 else 0
    page_eff = page_values / (exit_rate + 1e-5)
    bounce_exit_ratio = bounce / (exit_rate + 1e-5)
    weekend_returning = int(weekend and visitor_type == "Returning_Visitor")
    is_holiday = int(month in ["Nov", "Dec", "May"])

    data = {
        "Administrative": admin, "Administrative_Duration": admin_dur,
        "Informational": info, "Informational_Duration": info_dur,
        "ProductRelated": product, "ProductRelated_Duration": product_dur,
        "BounceRates": bounce, "ExitRates": exit_rate, "PageValues": page_values,
        "SpecialDay": special_day, "OperatingSystems": os_, "Browser": browser,
        "Region": region, "TrafficType": traffic, "Weekend": int(weekend),
        "Total_Pages_Viewed": total_pages, "Total_Duration": total_duration,
        "Avg_Duration_Per_Page": avg_dur_page, "ProductRelated_Ratio": product_ratio,
        "Page_Efficiency": page_eff, "Bounce_Exit_Ratio": bounce_exit_ratio,
        "Weekend_Returning": weekend_returning, "Is_Holiday_Season": is_holiday,
    }
    for m in ["Mar","May","June","Jul","Aug","Sep","Oct","Nov","Dec"]:
        data[f"Month_{m}"] = int(month == m)
    for v in ["New_Visitor", "Other"]:
        data[f"VisitorType_{v}"] = int(visitor_type == v)

    return pd.DataFrame([data])

input_df = user_input()

st.subheader("Session Feature Summary")
st.dataframe(input_df, use_container_width=True)

col1, col2 = st.columns([1, 1])
with col1:
    predict_clicked = st.button("🔮 Predict Purchase", use_container_width=True)
with col2:
    if st.button("🔄 Reset Inputs", use_container_width=True):
        st.rerun()

if predict_clicked:
    expected_cols = preprocessor.feature_names_in_ if hasattr(preprocessor, "feature_names_in_") else input_df.columns
    for col in expected_cols:
        if col not in input_df.columns:
            input_df[col] = 0
    input_df = input_df[expected_cols]

    X_proc = preprocessor.transform(input_df)
    proba = model.predict_proba(X_proc)[0][1]
    pred = int(proba >= 0.5)

    st.subheader("Prediction Result")
    label = "✅ Likely to Purchase" if pred == 1 else "❌ Unlikely to Purchase"
    st.markdown(f"### {label}")

    fig = go.Figure(go.Indicator(
        mode="gauge+number",
        value=proba * 100,
        title={"text": "Purchase Probability (%)"},
        gauge={"axis": {"range": [0, 100]},
               "bar": {"color": "#4C72B0"},
               "steps": [
                   {"range": [0, 40], "color": "#f8d7da"},
                   {"range": [40, 70], "color": "#fff3cd"},
                   {"range": [70, 100], "color": "#d4edda"}]}
    ))
    st.plotly_chart(fig, use_container_width=True)

    st.metric("Model Confidence", f"{max(proba, 1-proba)*100:.1f}%")

    result_df = input_df.copy()
    result_df["Predicted_Revenue"] = pred
    result_df["Purchase_Probability"] = proba
    st.download_button("⬇️ Download Prediction", result_df.to_csv(index=False),
                        file_name="prediction.csv", mime="text/csv")

st.markdown("---")
st.markdown("<center>Built for COM763 Advanced Machine Learning — Wrexham University</center>", unsafe_allow_html=True)
'''

with open("app.py", "w") as f:
    f.write(app_code)

print("app.py generated.")

requirements_txt = """streamlit
scikit-learn
pandas
numpy
xgboost
lightgbm
joblib
plotly
"""
with open("requirements.txt", "w") as f:
    f.write(requirements_txt)

runtime_txt = "python-3.11\n"
with open("runtime.txt", "w") as f:
    f.write(runtime_txt)

readme_md = f"""# Online Shopper Purchase Intention Predictor

A Streamlit web app that predicts whether an online shopping session will
result in a purchase, using a **{best_model_name}** model trained on the
Online Shoppers Intention dataset.

## Files
- `app.py` — Streamlit application
- `best_model.pkl` — trained classifier
- `preprocessor.pkl` — fitted ColumnTransformer/StandardScaler pipeline
- `requirements.txt` — Python dependencies
- `runtime.txt` — Python runtime version

## Run locally
```bash
pip install -r requirements.txt
streamlit run app.py
```

## Deploy on Streamlit Community Cloud
1. Push this folder to a public GitHub repository.
2. Go to https://share.streamlit.io and sign in with GitHub.
3. Click "New app", select the repository, branch, and `app.py` as the entry point.
4. Click "Deploy". Streamlit Cloud installs `requirements.txt` and runs the app.
5. Your app will be live at `https://<your-app-name>.streamlit.app`.
"""
with open("README.md", "w") as f:
    f.write(readme_md)

print("requirements.txt, runtime.txt, and README.md generated.")